/* tslint:disable */
/* eslint-disable */
/**
 * CodeCharacter API
 * Specification of the CodeCharacter API
 *
 * The version of the OpenAPI document: 2023.0.1
 * Contact: delta@nitt.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  DailyChallengeGetRequest,
  DailyChallengeLeaderBoardResponse,
} from '../models';

/**
 * DailyChallengesApi - interface
 *
 * @export
 * @interface DailyChallengesApiInterface
 */
export interface DailyChallengesApiInterface {
  /**
   * Get current user challenge for that day
   * @summary Get Daily Challenge for the day
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DailyChallengesApiInterface
   */
  getDailyChallengeRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<DailyChallengeGetRequest>>;

  /**
   * Get current user challenge for that day
   * Get Daily Challenge for the day
   */
  getDailyChallenge(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<DailyChallengeGetRequest>;

  /**
   * Get Leaderboard for daily challenges
   * @summary Get Daily Challenges Leaderboard
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DailyChallengesApiInterface
   */
  getDailyChallengeLeaderBoardRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<DailyChallengeLeaderBoardResponse>>>;

  /**
   * Get Leaderboard for daily challenges
   * Get Daily Challenges Leaderboard
   */
  getDailyChallengeLeaderBoard(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<DailyChallengeLeaderBoardResponse>>;
}

/**
 *
 */
export class DailyChallengesApi
  extends runtime.BaseAPI
  implements DailyChallengesApiInterface
{
  /**
   * Get current user challenge for that day
   * Get Daily Challenge for the day
   */
  async getDailyChallengeRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<DailyChallengeGetRequest>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('http-bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/dc/get`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get current user challenge for that day
   * Get Daily Challenge for the day
   */
  async getDailyChallenge(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<DailyChallengeGetRequest> {
    const response = await this.getDailyChallengeRaw(initOverrides);
    return await response.value();
  }

  /**
   * Get Leaderboard for daily challenges
   * Get Daily Challenges Leaderboard
   */
  async getDailyChallengeLeaderBoardRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<DailyChallengeLeaderBoardResponse>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('http-bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/dc/leaderboard`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Leaderboard for daily challenges
   * Get Daily Challenges Leaderboard
   */
  async getDailyChallengeLeaderBoard(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<DailyChallengeLeaderBoardResponse>> {
    const response = await this.getDailyChallengeLeaderBoardRaw(initOverrides);
    return await response.value();
  }
}
