/* tslint:disable */
/* eslint-disable */
/**
 * CodeCharacter API
 * Specification of the CodeCharacter API
 *
 * The version of the OpenAPI document: 2024.0.1
 * Contact: delta@nitt.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { PvPLeaderBoardResponse } from '../models/index';

export interface GetPvPLeaderboardRequest {
  page?: number;
  size?: number;
}

/**
 * PvpLeaderboardApi - interface
 *
 * @export
 * @interface PvpLeaderboardApiInterface
 */
export interface PvpLeaderboardApiInterface {
  /**
   * Get PvP leaderboard
   * @summary Get PvP leaderboard
   * @param {number} [page] Index of the page
   * @param {number} [size] Size of the page
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PvpLeaderboardApiInterface
   */
  getPvPLeaderboardRaw(
    requestParameters: GetPvPLeaderboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<PvPLeaderBoardResponse>>>;

  /**
   * Get PvP leaderboard
   * Get PvP leaderboard
   */
  getPvPLeaderboard(
    page?: number,
    size?: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<PvPLeaderBoardResponse>>;
}

/**
 *
 */
export class PvpLeaderboardApi
  extends runtime.BaseAPI
  implements PvpLeaderboardApiInterface
{
  /**
   * Get PvP leaderboard
   * Get PvP leaderboard
   */
  async getPvPLeaderboardRaw(
    requestParameters: GetPvPLeaderboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<PvPLeaderBoardResponse>>> {
    const queryParameters: any = {};

    if (requestParameters.page !== undefined) {
      queryParameters['page'] = requestParameters.page;
    }

    if (requestParameters.size !== undefined) {
      queryParameters['size'] = requestParameters.size;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('http-bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/pvpleaderboard`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get PvP leaderboard
   * Get PvP leaderboard
   */
  async getPvPLeaderboard(
    page?: number,
    size?: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<PvPLeaderBoardResponse>> {
    const response = await this.getPvPLeaderboardRaw(
      { page: page, size: size },
      initOverrides,
    );
    return await response.value();
  }
}
