/* tslint:disable */
/* eslint-disable */
/**
 * CodeCharacter API
 * Specification of the CodeCharacter API
 *
 * The version of the OpenAPI document: 2024.0.1
 * Contact: delta@nitt.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  CodeTutorialMatchRequest,
  GenericError,
  TutorialsGetRequest,
} from '../models';

export interface CreateCodeTutorialMatchRequest {
  codeTutorialMatchRequest: CodeTutorialMatchRequest;
}

export interface GetCodeTutorialByNumberRequest {
  codeTutorialNumber: number;
}

/**
 * TutorialsApi - interface
 *
 * @export
 * @interface TutorialsApiInterface
 */
export interface TutorialsApiInterface {
  /**
   * Match making for Tutorials
   * @summary Match Execution for Tutorials
   * @param {CodeTutorialMatchRequest} codeTutorialMatchRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TutorialsApiInterface
   */
  createCodeTutorialMatchRaw(
    requestParameters: CreateCodeTutorialMatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>;

  /**
   * Match making for Tutorials
   * Match Execution for Tutorials
   */
  createCodeTutorialMatch(
    codeTutorialMatchRequest: CodeTutorialMatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>;

  /**
   * Get a single tutorial
   * @summary Get tutorial by number
   * @param {number} codeTutorialNumber
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TutorialsApiInterface
   */
  getCodeTutorialByNumberRaw(
    requestParameters: GetCodeTutorialByNumberRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TutorialsGetRequest>>;

  /**
   * Get a single tutorial
   * Get tutorial by number
   */
  getCodeTutorialByNumber(
    codeTutorialNumber: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TutorialsGetRequest>;
}

/**
 *
 */
export class TutorialsApi
  extends runtime.BaseAPI
  implements TutorialsApiInterface
{
  /**
   * Match making for Tutorials
   * Match Execution for Tutorials
   */
  async createCodeTutorialMatchRaw(
    requestParameters: CreateCodeTutorialMatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (
      requestParameters.codeTutorialMatchRequest === null ||
      requestParameters.codeTutorialMatchRequest === undefined
    ) {
      throw new runtime.RequiredError(
        'codeTutorialMatchRequest',
        'Required parameter requestParameters.codeTutorialMatchRequest was null or undefined when calling createCodeTutorialMatch.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('http-bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/codetutorial/submit`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters.codeTutorialMatchRequest,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Match making for Tutorials
   * Match Execution for Tutorials
   */
  async createCodeTutorialMatch(
    codeTutorialMatchRequest: CodeTutorialMatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.createCodeTutorialMatchRaw(
      { codeTutorialMatchRequest: codeTutorialMatchRequest },
      initOverrides,
    );
  }

  /**
   * Get a single tutorial
   * Get tutorial by number
   */
  async getCodeTutorialByNumberRaw(
    requestParameters: GetCodeTutorialByNumberRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TutorialsGetRequest>> {
    if (
      requestParameters.codeTutorialNumber === null ||
      requestParameters.codeTutorialNumber === undefined
    ) {
      throw new runtime.RequiredError(
        'codeTutorialNumber',
        'Required parameter requestParameters.codeTutorialNumber was null or undefined when calling getCodeTutorialByNumber.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('http-bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/codetutorial/get/{codeTutorialNumber}`.replace(
          `{${'codeTutorialNumber'}}`,
          encodeURIComponent(String(requestParameters.codeTutorialNumber)),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a single tutorial
   * Get tutorial by number
   */
  async getCodeTutorialByNumber(
    codeTutorialNumber: number,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TutorialsGetRequest> {
    const response = await this.getCodeTutorialByNumberRaw(
      { codeTutorialNumber: codeTutorialNumber },
      initOverrides,
    );
    return await response.value();
  }
}
